### ISSUE TITLE
申请创建hpc-tuning-patches仓库

### ISSUE THREAD

**Issue by yip111** [kunpengcompute/Kunpeng#100]
## 1. 项目名称
> hpc-tuning-patches

## 2. 项目简介
> "hpc-tuning-patches" is a series of KunPeng optimization patches for open-source software. Users can get better performance with these patches

## 3. 确认License
> 与原软件license信息保持一致

## 4. 确认Matainer
> qinluyao761,yip111,StephonTone,yulin68,wubingcheng,daniceexi

**Comment by Yikun** [comment]
Close by https://github.com/kunpengcompute/Kunpeng/pull/101
