### ISSUE TITLE
openeuler系统中libpthread.so和libthread_db.so不匹配

### ISSUE THREAD

**Issue by yansendao** [kunpengcompute/Kunpeng#17]
test command：
```
sudo yum install java-1.8.0-openjdk.aarch64 java-1.8.0-openjdk-devel.aarch64
javac Hello.java
java Hello &
pid=$!
gdb --args jstack -F $pid
```

warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.

**Comment by Yikun** [comment]
@yansendao Hi, thanks for the issue, but looks like it's the issue shoud be raised in openEuler community. 

Would you mind the issue in [1]?

[1] https://gitee.com/openeuler/community-issue/issues

**Comment by yansendao** [comment]
https://gitee.com/openeuler/community-issue/issues/I1HAME?from=project-issue
