### ISSUE TITLE
鲲鹏920 mainline Linux kernel 支持情况，以及BSP内核源码。

### ISSUE THREAD

**Issue by zhangn1985** [kunpengcompute/Kunpeng#19]
因为已经有若干款鲲鹏920的台式机发布，那么想问一下，
1，Linux mainline 对鲲鹏920及其主板的支持情况？
2，哪里可以获得BSP内核？
3，为其定制操作系统，如何引导？

**Comment by Yikun** [comment]
@zhangn1985 你好，感谢关注。以下为从我个人角度的回答，请参考：
1. Linux mainline对arm64的支持是比较好的，因此，所有具有aarch64/arm64支持的发行版均是可以使用的。例如目前华为云的鲲鹏实例，主流的操作系统是可以使用的。
2. BSP内核我理解也是一样的。
3. 目前，针对鲲鹏有深度优化的操作系统，有openEuler，感兴趣可以看下https://openeuler.org/

**Comment by zhangn1985** [comment]
感谢回答，
1，我了解Linux kernel支持arm64，但是关键在于外围总线，设备，特别是主板的支持是不是存在。
2，https://gitee.com/openeuler/kernel 这应该是通用内核，但我还没来得及看。
3，我会仔细看这个社区的。

**Comment by Yikun** [comment]
@zhangn1985 我创建了一个issue在openEuler:

https://gitee.com/openeuler/community/issues/I1TAU1

希望可以帮到你。

**Comment by zhangn1985** [comment]
谢谢，回答非常详细。

**Comment by zhangn1985** [comment]
因为某宝可以买到，所以可以定制系统啦。

**Comment by Yikun** [comment]
@zhangn1985 好的，如果方便，可以将你的诉求在gitee的帖子里也描述下，用户的反馈对我们非常重要。谢谢。
