### ISSUE TITLE
申请创建hadoop-fs-ceph仓库

### ISSUE THREAD

**Issue by MacChen02** [kunpengcompute/Kunpeng#24]
## 1. 项目名称
> hadoop-fs-ceph

## 2. 项目简介
> 使用Ceph替代HDFS作为Hadoop的存储系统，使得大数据计算和存储资源分离，实现资源按需弹性扩展。

## 3. 确认License
> Apache V2

## 4. 确认Matainer
> MacChen02

**Comment by Yikun** [comment]
https://github.com/kunpengcompute/hadoop-fs-ceph
