### ISSUE TITLE
申请创建ceph仓库

### ISSUE THREAD

**Issue by aixiaorenzhe** [kunpengcompute/Kunpeng#46]
## 1. 项目名称
> 例如：Ceph

## 2. 项目简介
> Ceph with Kunpeng optimization

## 3. 确认License
> GPL3

## 4. 确认Matainer
> aixiaorenzhe  qinghaixiang

**Comment by Yikun** [comment]
https://github.com/kunpengcompute/Kunpeng/pull/47
