### ISSUE TITLE
申请创建robox仓库

### ISSUE THREAD

**Issue by wanglei0421** [kunpengcompute/Kunpeng#49]
## 1. 项目名称
>robox

## 2. 项目简介
>The robox is a container-based solution that can run multiple Android instances on Kunpeng servers.

## 3. 确认License
> GPLv3

## 4. 确认Matainer
> feijianqiang-wind,Bessel-Native,ZhaoPengyuan-suffix,wanglei0421

**Comment by Yikun** [comment]
https://github.com/kunpengcompute/Kunpeng/pull/50
