### ISSUE TITLE
申请创建KunpengSecL仓库

### ISSUE THREAD

**Issue by gwei3** [kunpengcompute/Kunpeng#53]
## 1. 项目名称
KunpengSecL

## 2. 项目简介
This project will collect, port, adapt, design and develop basic security software components running on Kunpeng processors such as security libraries, security middle wares, security tools, enabling Kunpeng security community and developers.

## 3. 确认License
Mulan PSL V2

## 4. 确认Matainer
gwei3, wucaijun2001

**Comment by Yikun** [comment]
https://github.com/kunpengcompute/Kunpeng/pull/54
