### ISSUE TITLE
申请创建devkitdriver仓库

### ISSUE THREAD

**Issue by chenych27** [kunpengcompute/Kunpeng#57]
## 1. 项目名称
> devkitdriver

## 2. 项目简介
> A group of dependent drivers for DevKit.

## 3. 确认License
> gccchecker: GPLV3
SVF: GPLV3
PMUdriver: GPLV2
SPEdriver: GPLV2
perfpatch: GPLV2

## 4. 确认Matainer
> ganli2015
yudi-work
chenych27

**Comment by Yikun** [comment]
Done
