### ISSUE TITLE
申请创建devkitdict仓库

### ISSUE THREAD

**Issue by wenhao2017** [kunpengcompute/Kunpeng#59]
## 1. 项目名称
Kunpeng Development Suite（鲲鹏开发套件）
## 2. 项目简介
华为帮助开发者加速应用迁移和算力升级，提供鲲鹏开发套件，包括分析扫描、代码迁移、鲲鹏加速库、编译调试和性能分析与优化等一系列工具
## 3. 确认License
Apache V2

## 4. 确认Matainer
wenhao2017

**Comment by Yikun** [comment]
Done
