### ISSUE TITLE
申请创建ftca仓库

### ISSUE THREAD

**Issue by ZijunYin** [kunpengcompute/Kunpeng#78]
## 1. 项目名称
ftca（操作系统与部件兼容性查询助手）

## 2. 项目简介
用于查询服务器在不同配置下对各个操作系统的兼容性，或查询服务器型号所兼容的各个部件。
Computing Product Compatibility Checker, used to check the compatibility of OSs and parts

## 3. 确认License
Apache V2

## 4. 确认Matainer
zijun.yin.zoe@gmail.com

**Comment by Yikun** [comment]
@ZijunYin https://github.com/kunpengcompute/Kunpeng#readme

Thanks, you need fullfill the project info in above readme.
